apiVersion: batch/v1
kind: Job
metadata:
  name: ansible-k8s-bootstrap
spec:
  backoffLimit: 3
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Never
      volumes:
      - name: repo
        emptyDir: {}
      - name: host-ssh
        secret:
          secretName: ansible-ssh-key
          defaultMode: 0400

      initContainers:
      - name: git-clone
        image: docker.io/alpine/git:latest
        workingDir: /repo
        command: ["sh", "-c", "git clone --depth 1 https://github.com/ProjectKIKI/k8s-ansible.v2.git /repo/k8s-ansible.v2"]
        volumeMounts:
        - name: repo
          mountPath: /repo

      containers:
      - name: ansible
        image: quay.io/ansible/ansible-runner:latest
        workingDir: /repo/k8s-ansible.v2/kube
        command: ["sh", "-c"]
        args:
        - |
          set -e
          echo "=== Ansible 환경 확인 ==="
          ansible --version
          python3 --version
          
          echo "=== 작업 디렉토리 확인 ==="
          pwd
          ls -la
          
          echo "=== SSH 키 디렉토리 상세 확인 ==="
          echo "SSH 키 디렉토리 내용:"
          ls -la /runner/ssh/
          echo "파일 상세 정보:"
          find /runner/ssh/ -type f -exec ls -la {} \;
          echo "파일 내용 확인 (처음 몇 줄):"
          find /runner/ssh/ -type f -exec head -2 {} \;
          
          echo "=== SSH 키 파일 설정 ==="
          # SSH 키 디렉토리 생성
          mkdir -p /tmp/ssh
          
          # SSH 키 파일 찾기 및 복사
          SSH_KEY_PATH=""
          if [ -f /runner/ssh/ssh-privatekey ]; then
            SSH_KEY_PATH="/runner/ssh/ssh-privatekey"
          elif [ -f /runner/ssh/id_rsa ]; then
            SSH_KEY_PATH="/runner/ssh/id_rsa"
          else
            # Symlink된 파일 찾기
            SSH_KEY_PATH=$(find /runner/ssh/ -name "*privatekey" -o -name "id_rsa" -o -name "ansible-ssh-key" | head -1)
            if [ -z "$SSH_KEY_PATH" ]; then
              # 모든 파일 중 첫 번째 파일 사용
              SSH_KEY_PATH=$(find /runner/ssh/ -type f | head -1)
            fi
          fi
          
          if [ -n "$SSH_KEY_PATH" ]; then
            echo "SSH 키 파일을 발견했습니다: $SSH_KEY_PATH"
            cp "$SSH_KEY_PATH" /tmp/ssh/ansible-ssh-key
            chmod 400 /tmp/ssh/ansible-ssh-key
            echo "SSH 키를 /tmp/ssh/ansible-ssh-key로 복사했습니다"
            ls -la /tmp/ssh/ansible-ssh-key
          else
            echo "ERROR: SSH 키 파일을 찾을 수 없습니다!"
            exit 1
          fi
          
          echo "=== Inventory 파일 수정 ==="
          # inventory 파일의 SSH 키 경로를 /tmp 경로로 강제 수정
          sed -i 's|ansible_ssh_private_key_file:.*|ansible_ssh_private_key_file: /tmp/ssh/ansible-ssh-key|g' inventory/kube.yaml
          
          # 추가로 그룹명도 수정 (하이픈을 언더스코어로)
          sed -i 's/k8s-/k8s_/g' inventory/kube.yaml
          
          echo "수정된 inventory 파일:"
          cat inventory/kube.yaml
          
          echo "=== SSH 키 테스트 ==="
          echo "SSH 키 설정 완료. Ansible ping 테스트로 연결 확인합니다."
          
          echo "=== 연결 테스트 ==="
          ansible all -i inventory/kube.yaml -m ping -v || echo "연결 테스트 실패 - 계속 진행"
          
          echo "=== Inventory 유효성 검사 ==="
          ansible-inventory -i inventory/kube.yaml --list
          
          echo "=== Playbook 수정 ==="
          # playbook의 hosts 그룹명도 수정
          sed -i 's/k8s-/k8s_/g' playbooks/cluster_setup.yaml
          
          echo "=== 클러스터 설치 시작 ==="
          chmod +x setup_cluster.sh
          
          # Ansible playbook 직접 실행 (setup_cluster.sh 대신)
          echo "=== 마스터 노드 설치 ==="
          ansible-playbook -i inventory/kube.yaml playbooks/cluster_setup.yaml --tags master -v || echo "마스터 노드 설치 실패"
          
          echo "=== 워커 노드 설치 ==="
          ansible-playbook -i inventory/kube.yaml playbooks/cluster_setup.yaml --tags worker -v || echo "워커 노드 설치 실패"
          
          echo "=== 클러스터 상태 확인 ==="
          ansible-playbook -i inventory/kube.yaml playbooks/cluster_setup.yaml --tags verify -v || echo "상태 확인 실패"
        env:
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "false"
        - name: ANSIBLE_SSH_RETRIES
          value: "3"
        - name: ANSIBLE_TIMEOUT
          value: "30"
        - name: ANSIBLE_SSH_ARGS
          value: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        volumeMounts:
        - name: repo
          mountPath: /repo
        - name: host-ssh
          mountPath: /runner/ssh
          readOnly: true 