all:
  children:
    k8s_cluster:
      children:
        k8s_controller:
          hosts:
            controller:
              ansible_host: 10.10.10.213
              node_hostname: node1.example.com
              node_role: master
        k8s_workers:
          children:
            k8s_compute1:
              hosts:
                compute1:
                  ansible_host: 10.10.10.14
                  node_hostname: node2.example.com
                  node_role: worker
            k8s_compute2:
              hosts:
                compute2:
                  ansible_host: 10.10.10.120
                  node_hostname: node3.example.com
                  node_role: worker
    k8s_infra:
      hosts:
        infra:
          ansible_host: 10.10.10.190
          node_hostname: infra.example.com
          node_role: infra
  vars:
    # 공통 변수들
    ansible_user: rocky
    # SSH 키 경로 - Pod 내에서 /tmp로 복사된 키 사용
    ansible_ssh_private_key_file: /tmp/ssh/ansible-ssh-key
    
    # Become 설정 (sudo 사용)
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
    
    # SSH 설정
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30'
    
    # Python 인터프리터 설정 (Rocky Linux의 경우)
    ansible_python_interpreter: /usr/bin/python3