plugin: openstack.cloud.openstack
auth:
  auth_url: http://vlab.dustbox.kr:5000/v3
  username: "jkb"
  password: "rkfaorltkf"
  project_name: "jkb"
  project_domain_name: "student"
  user_domain_name: "student"
keypairs:
  private_key_file: ~/Downloads/jkb.pem
region_name: RegionOne
interface: public
api_version: '3'
all:
  children:
    k8s-controller:
      hosts:
        root:
          ansible_host: 10.0.0.166
          ansible_user: root
          ansible_ssh_private_key_file: ~/jkb.pem
    k8s-infra:
      hosts:
        root:
          ansible_host: 10.0.0.136
    k8s-compute1:
      hosts:
        root:
          ansible_host: 10.0.0.2
    k8s-compute2:
      hosts:
        root:
          ansible_host: 10.0.0.??
          